name: gerar animação de cobra

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  gerar:
    runs-on: ubuntu-latest

    steps:
      - name: gerar github-contribution-grid-snake
        uses: Platane/snk@v3
        with:
          github_user_name: Developer-DaniloC
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: enviar cobra
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
